---
# Variables used in tasks:
# - openwrt_config_cron_contents (multi-line variable)

- name: Create root crontab file
  copy:
    content: "{{ openwrt_config_cron_contents }}"
    dest: /etc/crontabs/root
    owner: "root"
    group: "root"
    mode: "0600"
  when: openwrt_config_cron_contents is defined
  notify: Restart cron

- name: Enable and start service
  service:
    name: cron
    state: started
    enabled: true
  when: openwrt_config_cron_contents is defined
